on: [push]

name: rust-aoc CI/CD

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: "x86_64-unknown-linux-musl"

      - name: Lint
        run: make lint

      - name: Tests
        run: make tests

